### PR TITLE
DRAFT: testing freshness check from dbt metadata

### PR DESCRIPTION
**Pull request by slopp**
Needs to land after https://github.com/dagster-io/dagster/pull/22290

~Main question, @dpeng817 , do I also need to create a sensor for these checks?~

### CODE REVIEW

**Comment by dpeng817** [comment]
@slopp yea, you need to create a sensor.

**Comment by dpeng817** [comment]
You need to define the actual freshness SLA here as well: https://github.com/dagster-io/hooli-data-eng-pipelines/blob/master/dbt_project/models/schema.yml

**Comment by slopp** [comment]
Its alive 

@cnolanminich  I'd appreciate your thoughts on where I put the meta section given our dbt setup

Screen Shot 2024-06-10 at 1 30 18 PM

**Review by dpeng817 — APPROVED** [review]
LGTM from a product perspective. Not sure about actual SLAs etc.

**Review by cnolanminich — APPROVED** [review]
lgtm as well!

**Pull request merged**
